### ISSUE TITLE
Should socket connection work? I do only get a red circle

### ISSUE THREAD

**Issue by ramonbraunwarth** [benassa-de-glassa/brandi_dog#3]
I do only get a red circle (indicating no connection)?

Do I need to set up the connection manually after starting the frontend and backend servers?

**Comment by benassa-de-glassa** [comment]
AFAIK yes, maybe you have to login?

**Comment by ramonbraunwarth** [comment]
Creating user throws the following errors: 

- ERROR:uvicorn.error:Exception in ASGI application

- passlib.exc.MissingBackendError: bcrypt: no backends available -- recommend you install one (e.g. 'pip install bcrypt')

**Comment by benassa-de-glassa** [comment]
didnt bcrypt get installed when you ran pip install -r requirements.txt?

**Comment by ramonbraunwarth** [comment]
If I did that from the beginning, it would have ;) thx for the hint, it's working now.
